services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_DB: tickets
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

